// GENERATED BY SuperGate GTX Compiler (ggml/vision.cpp backend), DO NOT EDIT!
#pragma once
#include "visp/ml.h"

namespace visp {

struct DetectionModel_params {
    // TODO(ggml): 모델 하이퍼파라미터 (block_count 등)
};

VISP_API tensor DetectionModel_forward(model_ref m, tensor x, DetectionModel_params const& p);
VISP_API DetectionModel_params DetectionModel_detect_params(model_file const& f);

} // namespace visp
