// GENERATED BY SuperGate GTX Compiler (ggml/vision.cpp backend), DO NOT EDIT!
#pragma once
#include "visp/ml.h"

namespace visp {

struct ResNet_params {
    // TODO(ggml): 모델 하이퍼파라미터 (block_count 등)
};

VISP_API tensor ResNet_forward(model_ref m, tensor x, ResNet_params const& p);
VISP_API ResNet_params ResNet_detect_params(model_file const& f);

} // namespace visp
