// GENERATED BY SuperGate GTX Compiler (ggml/vision.cpp backend), DO NOT EDIT!
#include "visp/arch/DetectionModel.h"
#include "visp/ml.h"
#include "visp/nn.h"
#include "visp/vision.h"
#include "util/string.h"
#include <cstdio>

#include <string_view>

namespace visp {

tensor DetectionModel_forward(model_ref m, tensor x, DetectionModel_params const& p) {
    (void)p;
    // 입력 레이아웃 변환 (TODO: cwhn/whcn 자동 판별)
    x = cwhn_to_contiguous_2d(m, x);

    tensor const1 = ggml_arange(m, 0.5f, 1.0f, 1.0f) /* const 0.5 */;
    tensor const2 = ggml_arange(m, 0.5f, 1.0f, 1.0f) /* const 0.5 */;
    tensor const3 = ggml_arange(m, 0.5f, 1.0f, 1.0f) /* const 0.5 */;
    tensor const4 = ggml_arange(m, 0.5f, 1.0f, 1.0f) /* const 0.5 */;
    tensor const5 = ggml_arange(m, 0.5f, 1.0f, 1.0f) /* const 0.5 */;
    tensor const6 = ggml_arange(m, 0.5f, 1.0f, 1.0f) /* const 0.5 */;
    tensor const7 = ggml_arange(m, 2.0f, 2.5f, 1.0f) /* const 2.0 */;
    tensor conv8 = conv_2d(m["model.0.conv"], x, 2, 1);
    tensor act9 = ggml_silu_inplace(m, conv8);
    tensor conv10 = conv_2d(m["model.1.conv"], act9, 2, 1);
    tensor act11 = ggml_silu_inplace(m, conv10);
    tensor conv12 = conv_2d(m["model.2.cv1.conv"], act11, 1, 0);
    tensor act13 = ggml_silu_inplace(m, conv12);
    tensor sl14 = ggml_view_4d(m, act13, 160, 160, 16, 1, act13->nb[1], act13->nb[2], act13->nb[3], 0);
    tensor sl15 = ggml_view_4d(m, act13, 160, 160, 16, 1, act13->nb[1], act13->nb[2], act13->nb[3], 16*act13->nb[2]);
    tensor conv16 = conv_2d(m["model.2.m.0.cv1.conv"], sl15, 1, 1);
    tensor act17 = ggml_silu_inplace(m, conv16);
    tensor conv18 = conv_2d(m["model.2.m.0.cv2.conv"], act17, 1, 1);
    tensor act19 = ggml_silu_inplace(m, conv18);
    tensor add20 = ggml_add(m, sl15, act19);
    tensor cat21 = ggml_concat(m, ggml_concat(m, sl14, sl15, 2), add20, 2);
    tensor conv22 = conv_2d(m["model.2.cv2.conv"], cat21, 1, 0);
    tensor act23 = ggml_silu_inplace(m, conv22);
    tensor conv24 = conv_2d(m["model.3.conv"], act23, 2, 1);
    tensor act25 = ggml_silu_inplace(m, conv24);
    tensor conv26 = conv_2d(m["model.4.cv1.conv"], act25, 1, 0);
    tensor act27 = ggml_silu_inplace(m, conv26);
    tensor sl28 = ggml_view_4d(m, act27, 80, 80, 32, 1, act27->nb[1], act27->nb[2], act27->nb[3], 0);
    tensor sl29 = ggml_view_4d(m, act27, 80, 80, 32, 1, act27->nb[1], act27->nb[2], act27->nb[3], 32*act27->nb[2]);
    tensor conv30 = conv_2d(m["model.4.m.0.cv1.conv"], sl29, 1, 1);
    tensor act31 = ggml_silu_inplace(m, conv30);
    tensor conv32 = conv_2d(m["model.4.m.0.cv2.conv"], act31, 1, 1);
    tensor act33 = ggml_silu_inplace(m, conv32);
    tensor add34 = ggml_add(m, sl29, act33);
    tensor conv35 = conv_2d(m["model.4.m.1.cv1.conv"], add34, 1, 1);
    tensor act36 = ggml_silu_inplace(m, conv35);
    tensor conv37 = conv_2d(m["model.4.m.1.cv2.conv"], act36, 1, 1);
    tensor act38 = ggml_silu_inplace(m, conv37);
    tensor add39 = ggml_add(m, add34, act38);
    tensor cat40 = ggml_concat(m, ggml_concat(m, ggml_concat(m, sl28, sl29, 2), add34, 2), add39, 2);
    tensor conv41 = conv_2d(m["model.4.cv2.conv"], cat40, 1, 0);
    tensor act42 = ggml_silu_inplace(m, conv41);
    tensor conv43 = conv_2d(m["model.5.conv"], act42, 2, 1);
    tensor act44 = ggml_silu_inplace(m, conv43);
    tensor conv45 = conv_2d(m["model.6.cv1.conv"], act44, 1, 0);
    tensor act46 = ggml_silu_inplace(m, conv45);
    tensor sl47 = ggml_view_4d(m, act46, 40, 40, 64, 1, act46->nb[1], act46->nb[2], act46->nb[3], 0);
    tensor sl48 = ggml_view_4d(m, act46, 40, 40, 64, 1, act46->nb[1], act46->nb[2], act46->nb[3], 64*act46->nb[2]);
    tensor conv49 = conv_2d(m["model.6.m.0.cv1.conv"], sl48, 1, 1);
    tensor act50 = ggml_silu_inplace(m, conv49);
    tensor conv51 = conv_2d(m["model.6.m.0.cv2.conv"], act50, 1, 1);
    tensor act52 = ggml_silu_inplace(m, conv51);
    tensor add53 = ggml_add(m, sl48, act52);
    tensor conv54 = conv_2d(m["model.6.m.1.cv1.conv"], add53, 1, 1);
    tensor act55 = ggml_silu_inplace(m, conv54);
    tensor conv56 = conv_2d(m["model.6.m.1.cv2.conv"], act55, 1, 1);
    tensor act57 = ggml_silu_inplace(m, conv56);
    tensor add58 = ggml_add(m, add53, act57);
    tensor cat59 = ggml_concat(m, ggml_concat(m, ggml_concat(m, sl47, sl48, 2), add53, 2), add58, 2);
    tensor conv60 = conv_2d(m["model.6.cv2.conv"], cat59, 1, 0);
    tensor act61 = ggml_silu_inplace(m, conv60);
    tensor conv62 = conv_2d(m["model.7.conv"], act61, 2, 1);
    tensor act63 = ggml_silu_inplace(m, conv62);
    tensor conv64 = conv_2d(m["model.8.cv1.conv"], act63, 1, 0);
    tensor act65 = ggml_silu_inplace(m, conv64);
    tensor sl66 = ggml_view_4d(m, act65, 20, 20, 128, 1, act65->nb[1], act65->nb[2], act65->nb[3], 0);
    tensor sl67 = ggml_view_4d(m, act65, 20, 20, 128, 1, act65->nb[1], act65->nb[2], act65->nb[3], 128*act65->nb[2]);
    tensor conv68 = conv_2d(m["model.8.m.0.cv1.conv"], sl67, 1, 1);
    tensor act69 = ggml_silu_inplace(m, conv68);
    tensor conv70 = conv_2d(m["model.8.m.0.cv2.conv"], act69, 1, 1);
    tensor act71 = ggml_silu_inplace(m, conv70);
    tensor add72 = ggml_add(m, sl67, act71);
    tensor cat73 = ggml_concat(m, ggml_concat(m, sl66, sl67, 2), add72, 2);
    tensor conv74 = conv_2d(m["model.8.cv2.conv"], cat73, 1, 0);
    tensor act75 = ggml_silu_inplace(m, conv74);
    tensor conv76 = conv_2d(m["model.9.cv1.conv"], act75, 1, 0);
    tensor act77 = ggml_silu_inplace(m, conv76);
    tensor pool78 = ggml_pool_2d(m, act77, GGML_OP_POOL_MAX, 5, 5, 1, 1, 2, 2);
    tensor pool79 = ggml_pool_2d(m, pool78, GGML_OP_POOL_MAX, 5, 5, 1, 1, 2, 2);
    tensor pool80 = ggml_pool_2d(m, pool79, GGML_OP_POOL_MAX, 5, 5, 1, 1, 2, 2);
    tensor cat81 = ggml_concat(m, ggml_concat(m, ggml_concat(m, act77, pool78, 2), pool79, 2), pool80, 2);
    tensor conv82 = conv_2d(m["model.9.cv2.conv"], cat81, 1, 0);
    tensor act83 = ggml_silu_inplace(m, conv82);
    tensor up84 = ggml_interpolate(m, act83, 40, 40, 256, 1, GGML_SCALE_MODE_NEAREST) /* interpolate -> target ne */;
    tensor cat85 = ggml_concat(m, up84, act61, 2);
    tensor conv86 = conv_2d(m["model.12.cv1.conv"], cat85, 1, 0);
    tensor act87 = ggml_silu_inplace(m, conv86);
    tensor sl88 = ggml_view_4d(m, act87, 40, 40, 64, 1, act87->nb[1], act87->nb[2], act87->nb[3], 0);
    tensor sl89 = ggml_view_4d(m, act87, 40, 40, 64, 1, act87->nb[1], act87->nb[2], act87->nb[3], 64*act87->nb[2]);
    tensor conv90 = conv_2d(m["model.12.m.0.cv1.conv"], sl89, 1, 1);
    tensor act91 = ggml_silu_inplace(m, conv90);
    tensor conv92 = conv_2d(m["model.12.m.0.cv2.conv"], act91, 1, 1);
    tensor act93 = ggml_silu_inplace(m, conv92);
    tensor cat94 = ggml_concat(m, ggml_concat(m, sl88, sl89, 2), act93, 2);
    tensor conv95 = conv_2d(m["model.12.cv2.conv"], cat94, 1, 0);
    tensor act96 = ggml_silu_inplace(m, conv95);
    tensor up97 = ggml_interpolate(m, act96, 80, 80, 128, 1, GGML_SCALE_MODE_NEAREST) /* interpolate -> target ne */;
    tensor cat98 = ggml_concat(m, up97, act42, 2);
    tensor conv99 = conv_2d(m["model.15.cv1.conv"], cat98, 1, 0);
    tensor act100 = ggml_silu_inplace(m, conv99);
    tensor sl101 = ggml_view_4d(m, act100, 80, 80, 32, 1, act100->nb[1], act100->nb[2], act100->nb[3], 0);
    tensor sl102 = ggml_view_4d(m, act100, 80, 80, 32, 1, act100->nb[1], act100->nb[2], act100->nb[3], 32*act100->nb[2]);
    tensor conv103 = conv_2d(m["model.15.m.0.cv1.conv"], sl102, 1, 1);
    tensor act104 = ggml_silu_inplace(m, conv103);
    tensor conv105 = conv_2d(m["model.15.m.0.cv2.conv"], act104, 1, 1);
    tensor act106 = ggml_silu_inplace(m, conv105);
    tensor cat107 = ggml_concat(m, ggml_concat(m, sl101, sl102, 2), act106, 2);
    tensor conv108 = conv_2d(m["model.15.cv2.conv"], cat107, 1, 0);
    tensor act109 = ggml_silu_inplace(m, conv108);
    tensor conv110 = conv_2d(m["model.16.conv"], act109, 2, 1);
    tensor act111 = ggml_silu_inplace(m, conv110);
    tensor cat112 = ggml_concat(m, act111, act96, 2);
    tensor conv113 = conv_2d(m["model.18.cv1.conv"], cat112, 1, 0);
    tensor act114 = ggml_silu_inplace(m, conv113);
    tensor sl115 = ggml_view_4d(m, act114, 40, 40, 64, 1, act114->nb[1], act114->nb[2], act114->nb[3], 0);
    tensor sl116 = ggml_view_4d(m, act114, 40, 40, 64, 1, act114->nb[1], act114->nb[2], act114->nb[3], 64*act114->nb[2]);
    tensor conv117 = conv_2d(m["model.18.m.0.cv1.conv"], sl116, 1, 1);
    tensor act118 = ggml_silu_inplace(m, conv117);
    tensor conv119 = conv_2d(m["model.18.m.0.cv2.conv"], act118, 1, 1);
    tensor act120 = ggml_silu_inplace(m, conv119);
    tensor cat121 = ggml_concat(m, ggml_concat(m, sl115, sl116, 2), act120, 2);
    tensor conv122 = conv_2d(m["model.18.cv2.conv"], cat121, 1, 0);
    tensor act123 = ggml_silu_inplace(m, conv122);
    tensor conv124 = conv_2d(m["model.19.conv"], act123, 2, 1);
    tensor act125 = ggml_silu_inplace(m, conv124);
    tensor cat126 = ggml_concat(m, act125, act83, 2);
    tensor conv127 = conv_2d(m["model.21.cv1.conv"], cat126, 1, 0);
    tensor act128 = ggml_silu_inplace(m, conv127);
    tensor sl129 = ggml_view_4d(m, act128, 20, 20, 128, 1, act128->nb[1], act128->nb[2], act128->nb[3], 0);
    tensor sl130 = ggml_view_4d(m, act128, 20, 20, 128, 1, act128->nb[1], act128->nb[2], act128->nb[3], 128*act128->nb[2]);
    tensor conv131 = conv_2d(m["model.21.m.0.cv1.conv"], sl130, 1, 1);
    tensor act132 = ggml_silu_inplace(m, conv131);
    tensor conv133 = conv_2d(m["model.21.m.0.cv2.conv"], act132, 1, 1);
    tensor act134 = ggml_silu_inplace(m, conv133);
    tensor cat135 = ggml_concat(m, ggml_concat(m, sl129, sl130, 2), act134, 2);
    tensor conv136 = conv_2d(m["model.21.cv2.conv"], cat135, 1, 0);
    tensor act137 = ggml_silu_inplace(m, conv136);
    tensor conv138 = conv_2d(m["model.22.cv2.0.0.conv"], act109, 1, 1);
    tensor act139 = ggml_silu_inplace(m, conv138);
    tensor conv140 = conv_2d(m["model.22.cv2.0.1.conv"], act139, 1, 1);
    tensor act141 = ggml_silu_inplace(m, conv140);
    tensor conv142 = conv_2d(m["model.22.cv2.0.2"], act141, 1, 0);
    tensor rs143 = ggml_reshape_3d(m, ggml_cont(m, conv142), 6400, 64, 1);
    tensor conv144 = conv_2d(m["model.22.cv2.1.0.conv"], act123, 1, 1);
    tensor act145 = ggml_silu_inplace(m, conv144);
    tensor conv146 = conv_2d(m["model.22.cv2.1.1.conv"], act145, 1, 1);
    tensor act147 = ggml_silu_inplace(m, conv146);
    tensor conv148 = conv_2d(m["model.22.cv2.1.2"], act147, 1, 0);
    tensor rs149 = ggml_reshape_3d(m, ggml_cont(m, conv148), 1600, 64, 1);
    tensor conv150 = conv_2d(m["model.22.cv2.2.0.conv"], act137, 1, 1);
    tensor act151 = ggml_silu_inplace(m, conv150);
    tensor conv152 = conv_2d(m["model.22.cv2.2.1.conv"], act151, 1, 1);
    tensor act153 = ggml_silu_inplace(m, conv152);
    tensor conv154 = conv_2d(m["model.22.cv2.2.2"], act153, 1, 0);
    tensor rs155 = ggml_reshape_3d(m, ggml_cont(m, conv154), 400, 64, 1);
    tensor cat156 = ggml_concat(m, ggml_concat(m, rs143, rs149, 0), rs155, 0);
    tensor conv157 = conv_2d(m["model.22.cv3.0.0.conv"], act109, 1, 1);
    tensor act158 = ggml_silu_inplace(m, conv157);
    tensor conv159 = conv_2d(m["model.22.cv3.0.1.conv"], act158, 1, 1);
    tensor act160 = ggml_silu_inplace(m, conv159);
    tensor conv161 = conv_2d(m["model.22.cv3.0.2"], act160, 1, 0);
    tensor rs162 = ggml_reshape_3d(m, ggml_cont(m, conv161), 6400, 80, 1);
    tensor conv163 = conv_2d(m["model.22.cv3.1.0.conv"], act123, 1, 1);
    tensor act164 = ggml_silu_inplace(m, conv163);
    tensor conv165 = conv_2d(m["model.22.cv3.1.1.conv"], act164, 1, 1);
    tensor act166 = ggml_silu_inplace(m, conv165);
    tensor conv167 = conv_2d(m["model.22.cv3.1.2"], act166, 1, 0);
    tensor rs168 = ggml_reshape_3d(m, ggml_cont(m, conv167), 1600, 80, 1);
    tensor conv169 = conv_2d(m["model.22.cv3.2.0.conv"], act137, 1, 1);
    tensor act170 = ggml_silu_inplace(m, conv169);
    tensor conv171 = conv_2d(m["model.22.cv3.2.1.conv"], act170, 1, 1);
    tensor act172 = ggml_silu_inplace(m, conv171);
    tensor conv173 = conv_2d(m["model.22.cv3.2.2"], act172, 1, 0);
    tensor rs174 = ggml_reshape_3d(m, ggml_cont(m, conv173), 400, 80, 1);
    tensor cat175 = ggml_concat(m, ggml_concat(m, rs162, rs168, 0), rs174, 0);
    tensor ar176 = ggml_arange(m, 0.0f, 80.0f, 1.0f);
    tensor add177 = ggml_add(m, ar176, const6);
    tensor ar178 = ggml_arange(m, 0.0f, 80.0f, 1.0f);
    tensor add179 = ggml_add(m, ar178, const5);
    tensor mgc180 = ggml_reshape_2d(m, add179, 1, 80);
    tensor mg181 = ggml_repeat(m, mgc180, ggml_new_tensor_2d(m, GGML_TYPE_F32, 80, 80));
    tensor mg182 = ggml_repeat(m, add177, ggml_new_tensor_2d(m, GGML_TYPE_F32, 80, 80));
    tensor stk183 = ggml_concat(m, ggml_reshape_3d(m, mg182, 1, 80, 80), ggml_reshape_3d(m, mg181, 1, 80, 80), 0);
    tensor rs184 = ggml_reshape_2d(m, ggml_cont(m, stk183), 2, 6400);
    tensor full186 = ggml_fill(m, ggml_new_tensor_2d(m, GGML_TYPE_F32, 1, 6400), 8.0f);
    tensor ar187 = ggml_arange(m, 0.0f, 40.0f, 1.0f);
    tensor add188 = ggml_add(m, ar187, const4);
    tensor ar189 = ggml_arange(m, 0.0f, 40.0f, 1.0f);
    tensor add190 = ggml_add(m, ar189, const3);
    tensor mgc191 = ggml_reshape_2d(m, add190, 1, 40);
    tensor mg192 = ggml_repeat(m, mgc191, ggml_new_tensor_2d(m, GGML_TYPE_F32, 40, 40));
    tensor mg193 = ggml_repeat(m, add188, ggml_new_tensor_2d(m, GGML_TYPE_F32, 40, 40));
    tensor stk194 = ggml_concat(m, ggml_reshape_3d(m, mg193, 1, 40, 40), ggml_reshape_3d(m, mg192, 1, 40, 40), 0);
    tensor rs195 = ggml_reshape_2d(m, ggml_cont(m, stk194), 2, 1600);
    tensor full197 = ggml_fill(m, ggml_new_tensor_2d(m, GGML_TYPE_F32, 1, 1600), 16.0f);
    tensor ar198 = ggml_arange(m, 0.0f, 20.0f, 1.0f);
    tensor add199 = ggml_add(m, ar198, const2);
    tensor ar200 = ggml_arange(m, 0.0f, 20.0f, 1.0f);
    tensor add201 = ggml_add(m, ar200, const1);
    tensor mgc202 = ggml_reshape_2d(m, add201, 1, 20);
    tensor mg203 = ggml_repeat(m, mgc202, ggml_new_tensor_2d(m, GGML_TYPE_F32, 20, 20));
    tensor mg204 = ggml_repeat(m, add199, ggml_new_tensor_2d(m, GGML_TYPE_F32, 20, 20));
    tensor stk205 = ggml_concat(m, ggml_reshape_3d(m, mg204, 1, 20, 20), ggml_reshape_3d(m, mg203, 1, 20, 20), 0);
    tensor rs206 = ggml_reshape_2d(m, ggml_cont(m, stk205), 2, 400);
    tensor full208 = ggml_fill(m, ggml_new_tensor_2d(m, GGML_TYPE_F32, 1, 400), 32.0f);
    tensor cat209 = ggml_concat(m, ggml_concat(m, rs184, rs195, 1), rs206, 1);
    tensor cat210 = ggml_concat(m, ggml_concat(m, full186, full197, 1), full208, 1);
    tensor t211 = ggml_cont(m, ggml_permute(m, cat209, 1, 0, 2, 3));
    tensor t212 = ggml_cont(m, ggml_permute(m, cat210, 1, 0, 2, 3));
    tensor rs213 = ggml_reshape_4d(m, ggml_cont(m, cat156), 8400, 16, 4, 1);
    tensor t214 = ggml_cont(m, ggml_permute(m, rs213, 0, 2, 1, 3));
    tensor sm215 = ggml_cont(m, ggml_permute(m, ggml_soft_max(m, ggml_cont(m, ggml_permute(m, t214, 2, 1, 0, 3))), 2, 1, 0, 3));
    tensor conv216 = conv_2d(m["model.22.dfl.conv"], sm215, 1, 0);
    tensor rs217 = ggml_reshape_3d(m, ggml_cont(m, conv216), 8400, 4, 1);
    tensor uns218 = ggml_reshape_3d(m, ggml_cont(m, t211), 8400, 2, 1);
    tensor sl219 = ggml_view_3d(m, rs217, 8400, 2, 1, rs217->nb[1], rs217->nb[2], 0);
    tensor sl220 = ggml_view_3d(m, rs217, 8400, 2, 1, rs217->nb[1], rs217->nb[2], 2*rs217->nb[1]);
    tensor t221 = ggml_sub(m, uns218, sl219);
    tensor add222 = ggml_add(m, uns218, sl220);
    tensor add223 = ggml_add(m, t221, add222);
    tensor div224 = ggml_div(m, add223, const7);
    tensor t225 = ggml_sub(m, add222, t221);
    tensor cat226 = ggml_concat(m, div224, t225, 1);
    tensor t227 = ggml_mul(m, cat226, t212);
    tensor t228 = ggml_sigmoid(m, cat175);
    tensor cat229 = ggml_concat(m, t227, t228, 1);

    tensor out_0 = compute_graph_output(m, contiguous_2d_to_cwhn(m, cat229), "out_0");
    tensor out_1 = compute_graph_output(m, contiguous_2d_to_cwhn(m, cat156), "out_1");
    tensor out_2 = compute_graph_output(m, contiguous_2d_to_cwhn(m, act109), "out_2");
    tensor out_3 = compute_graph_output(m, contiguous_2d_to_cwhn(m, act123), "out_3");
    tensor out_4 = compute_graph_output(m, contiguous_2d_to_cwhn(m, act137), "out_4");
    tensor out_5 = compute_graph_output(m, contiguous_2d_to_cwhn(m, cat175), "out_5");
    return out_0;
}

DetectionModel_params DetectionModel_detect_params(model_file const& f) {
    DetectionModel_params p{};
    // GGUF general.architecture 검증 (모델은 정적 unroll 이라 추가 하이퍼파라미터 없음).
    if (std::string_view arch = f.arch(); arch != "detectionmodel") {
        throw except(
            "Architecture expected to be 'detectionmodel', but was '{}' ({})",
            arch, f.path);
    }
    return p;
}

} // namespace visp
