// GENERATED BY SuperGate GTX Compiler (ggml/vision.cpp backend), DO NOT EDIT!
#include "visp/arch/ResNet.h"
#include "visp/ml.h"
#include "visp/nn.h"
#include "visp/vision.h"
#include "util/string.h"
#include <cstdio>

#include <string_view>

namespace visp {

tensor ResNet_forward(model_ref m, tensor x, ResNet_params const& p) {
    (void)p;
    // 입력 레이아웃 변환 (TODO: cwhn/whcn 자동 판별)
    x = cwhn_to_contiguous_2d(m, x);

    tensor conv1 = conv_2d(m["conv1"], x, 2, 3);
    tensor act2 = ggml_relu(m, conv1);
    tensor pool3 = ggml_pool_2d(m, act2, GGML_OP_POOL_MAX, 3, 3, 2, 2, 1, 1);
    tensor conv4 = conv_2d(m["layer1.0.conv1"], pool3, 1, 1);
    tensor act5 = ggml_relu(m, conv4);
    tensor conv6 = conv_2d(m["layer1.0.conv2"], act5, 1, 1);
    tensor add7 = ggml_add(m, conv6, pool3);
    tensor act8 = ggml_relu(m, add7);
    tensor conv9 = conv_2d(m["layer1.1.conv1"], act8, 1, 1);
    tensor act10 = ggml_relu(m, conv9);
    tensor conv11 = conv_2d(m["layer1.1.conv2"], act10, 1, 1);
    tensor add12 = ggml_add(m, conv11, act8);
    tensor act13 = ggml_relu(m, add12);
    tensor conv14 = conv_2d(m["layer2.0.conv1"], act13, 2, 1);
    tensor act15 = ggml_relu(m, conv14);
    tensor conv16 = conv_2d(m["layer2.0.conv2"], act15, 1, 1);
    tensor conv17 = conv_2d(m["layer2.0.downsample.0"], act13, 2, 0);
    tensor add18 = ggml_add(m, conv16, conv17);
    tensor act19 = ggml_relu(m, add18);
    tensor conv20 = conv_2d(m["layer2.1.conv1"], act19, 1, 1);
    tensor act21 = ggml_relu(m, conv20);
    tensor conv22 = conv_2d(m["layer2.1.conv2"], act21, 1, 1);
    tensor add23 = ggml_add(m, conv22, act19);
    tensor act24 = ggml_relu(m, add23);
    tensor conv25 = conv_2d(m["layer3.0.conv1"], act24, 2, 1);
    tensor act26 = ggml_relu(m, conv25);
    tensor conv27 = conv_2d(m["layer3.0.conv2"], act26, 1, 1);
    tensor conv28 = conv_2d(m["layer3.0.downsample.0"], act24, 2, 0);
    tensor add29 = ggml_add(m, conv27, conv28);
    tensor act30 = ggml_relu(m, add29);
    tensor conv31 = conv_2d(m["layer3.1.conv1"], act30, 1, 1);
    tensor act32 = ggml_relu(m, conv31);
    tensor conv33 = conv_2d(m["layer3.1.conv2"], act32, 1, 1);
    tensor add34 = ggml_add(m, conv33, act30);
    tensor act35 = ggml_relu(m, add34);
    tensor conv36 = conv_2d(m["layer4.0.conv1"], act35, 2, 1);
    tensor act37 = ggml_relu(m, conv36);
    tensor conv38 = conv_2d(m["layer4.0.conv2"], act37, 1, 1);
    tensor conv39 = conv_2d(m["layer4.0.downsample.0"], act35, 2, 0);
    tensor add40 = ggml_add(m, conv38, conv39);
    tensor act41 = ggml_relu(m, add40);
    tensor conv42 = conv_2d(m["layer4.1.conv1"], act41, 1, 1);
    tensor act43 = ggml_relu(m, conv42);
    tensor conv44 = conv_2d(m["layer4.1.conv2"], act43, 1, 1);
    tensor add45 = ggml_add(m, conv44, act41);
    tensor act46 = ggml_relu(m, add45);
    tensor pool47 = ggml_pool_2d(m, act46, GGML_OP_POOL_AVG, 7, 7, 7, 7, 0, 0);
    tensor flat48 = ggml_reshape_2d(m, ggml_cont(m, pool47), 512, 1);
    tensor fc49 = linear(m["fc"], flat48);

    tensor out_0 = compute_graph_output(m, contiguous_2d_to_cwhn(m, fc49), "out_0");
    return out_0;
}

ResNet_params ResNet_detect_params(model_file const& f) {
    ResNet_params p{};
    // GGUF general.architecture 검증 (모델은 정적 unroll 이라 추가 하이퍼파라미터 없음).
    if (std::string_view arch = f.arch(); arch != "resnet") {
        throw except(
            "Architecture expected to be 'resnet', but was '{}' ({})",
            arch, f.path);
    }
    return p;
}

} // namespace visp
